[package]
name = "governance"
version = "0.1.0"
description = "Contracts for governance of Starknet-native protocols"
homepage = "https://ekubo.org"
cairo-version = "2.3.0-rc0"

[dependencies]
starknet = "=2.3.0-rc0"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
